### ISSUE TITLE
The asset "application.js" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by almeidaz** [kirillplatonov/shopify-hotwire-sample#13]
Hi, i'm trying to play with your app because it's up to date with app bridge 2 but i'm facing this error

![Shopify-err2](https://user-images.githubusercontent.com/11940920/141597133-00218f98-db67-4972-83b4-d1d75940d8f9.png)

Did you have any idea to resolve this problem? Thanks. 

-------------
Windows 10
launching server with : 
rails server

**Comment by kirillplatonov** [comment]
Hey, you need to use `bin/dev` command to start the server. It will start both rails server and esbuild process that will generate `application.js`. This app uses new `jsbundling-rails` gem: https://github.com/rails/jsbundling-rails

**Comment by almeidaz** [comment]
Many thanks for reply.
Now i have to figured out how to use  "build": "esbuild app/javascript/*.* on windows cause *.* syntax is not support on windows. I have to manually list the entrypoints.
[info here](https://github.com/rails/jsbundling-rails/commit/95e6b15d02153e852712212c666af17a45f45d15)

For the moment i'm launching esbuild with Ubuntu with WSL and launching rails server with windows.
LiveReload and Polaris is pretty cool.

**Comment by kirillplatonov** [comment]
Didn't know about the glob issue on Windows. Great to hear you figured it out!
