### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#16]
The first command listed for this example App is 

     shopify rails connect

What does that command do? The typical developer command line response for the command shopify is the CLI from Shopify, which has no sub-command rails. What is this command for? What does it do? What would be a good alternative?

**Comment by kirillplatonov** [comment]
It seems to be changed in Shopify CLI. The new name for this command is: `shopify app connect`
It's used to generate `.env` file with API credentials.

**Comment by kirillplatonov** [comment]
Updated README. Thanks for noticing that.
