### ISSUE TITLE
bin/setup fails

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#17]
I am using Ruby 3.0.3

Trying the bin/setup on a brand new clone of this App. Database preparation step fails. The fix is to ensure bootsnap 1.9.3 or better is used, as earlier version bug out.

    bin/setup
    == Installing dependencies ==
    The Gemfile's dependencies are satisfied
    yarn install v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    ✨  Done in 9.51s.
    
    == Preparing database ==
    /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/iseq.rb:13:in `to_binary': wrong argument type false (expected Symbol) (TypeError)
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/iseq.rb:13:in `input_to_storage'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/iseq.rb:55:in `load_iseq'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/thor-1.1.0/lib/thor.rb:1:in `<main>'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/railties-6.1.4.1/lib/rails/command.rb:7:in `<main>'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/railties-6.1.4.1/lib/rails/commands.rb:3:in `<main>'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
    	from /Users/punkrock/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
    	from bin/rails:4:in `<main>'
    
    == Command ["bin/rails db:prepare"] failed ==

**Comment by kirillplatonov** [comment]
Fixed. Thanks!
