### ISSUE TITLE
So far so good!

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#18]
I installed puma ngrok tunneling. Set up puma-dev to respond to drunk-sailor.test, and then hacked in the needed configurations allowing for ngrok tunnels. 

Running foreman on a Procfile.dev with Sidekiq added and lo-and=behold, it all worked. This is **NOT** Rails 7 but still, I am happy to be on Ruby 3.0.3 and running a Rails Shopify App without being stuck in lalalala land with Shopify. 

I hope to be able to contribute where possible. I think I have a sweet development environment going, but, I am unable to join the 99% as I still make zero effort to write tests. Hence I may be useless around here as most modern people probably write tests before they do anything. 

Anyway, just wanted to say thanks.

**Comment by kirillplatonov** [comment]
Happy to hear you have a working setup! 🙂
Any contribution is very welcome. We have a pretty small community in Shopify app ecosystem compared to NodeJS. So every one support matters.
