### ISSUE TITLE
Render with Flash Messages

### ISSUE THREAD

**Issue by Jonathan-Garber** [kirillplatonov/shopify-hotwire-sample#2]
Trying to return to a form and show toast/flash message at same time.
```
render :edit, status: :unprocessable_entity, error: "Something Broke"
```
Form validation errors display as expected but I am not sure how to update the flash messages to get them to display in this manner. Is this even possible here?

I'm still working out how everything is tied together with hotwire, webpacker, javascripts etc.

I've considered just pushing a custom error to form validation messages but I prefer the toast/flash

**Comment by Jonathan-Garber** [comment]
Resolved - will type up resolution shortly.

**Comment by kirillplatonov** [comment]
Great, I highly recommend going through [Turbo Handbook](https://turbo.hotwired.dev/handbook/introduction).
And check this series of videos from Chris about Hotwire: https://gorails.com/series/hotwire-rails

**Comment by Jonathan-Garber** [comment]
Wrapped a turbo frame tag around the division that holds the flash data. This allowed me to update this div correctly when rendering the response. Then I used turbo:render to listen for the updated render and check for flash messages.

Working good so far.

**Comment by Jonathan-Garber** [comment]
Actually I found a cleaner solution -- forget the turbo_frame -- just use flash.now and listen for turbo:render
this still properly updates the flash messages and allows javascript to catch and display the toast

**Comment by Jonathan-Garber** [comment]
That is exactly where I added it 
flash_message.js

Same code used for "turbo:load" justs re-used it to listen on render.
