### ISSUE TITLE
Decorating Cards

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#21]
Polaris is rock botton when it comes to some aspects of design. In the past, what I did was to decorate it with custom HTML and CSS. So for example, when I want to display a merchant Logo, I would render a Card and then in that card, use a div to render an img tag. 

    <Card.Section className="container max-w-full mx-auto">
      <div>
        <img src={imagePath('./logo.png')} className="object-center object-contain h-48 w-full p-2" />
      </div>
    </Card.Section>

So this served me well, and I was able to make nice Cards with images, using Tailwind CSS for the control that Polaris does not offer. 

Long story short, if I get Tailwind to compile and work within my project (it used PostCSS so should not pose too much trouble), I would then be wanting to access an image, and render a Card like this. Thing is, do the ViewComponent versions of Polaris allow this? I am sure they do, but I am not 100%, it is a lot for me to digest right now. 

I know the Webpack version had me placing all CSS and images under /javascript but I think this technique of using esbuild means the older asset pipeline is still in play? Is that true? Is this a Sprockets kind of App where app/assets are still accessed and used? 

Any thoughts?

**Comment by kirillplatonov** [comment]
Yeah, you can add custom classes via `classes` attribute in Polaris ViewComponents:
```erb
<%= polaris_card_section(classes: "container max-w-full mx-auto") do %>
  ...
<% end %>
```

Mixing Polaris with Tailwind is an interesting idea. I also miss some utility classes from time to time. The easiest way to add Tailwind at this point will be [cssbundling-rails](https://github.com/rails/cssbundling-rails) gem.

This sample app uses old good sprockets for CSS and images. Polaris ViewComponents integrated with it out of the box. And the `CSS bundling-rails` gem also integrates Tailwind with sprockets so it's a very straightforward setup.

**Comment by kirillplatonov** [comment]
https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/views/layouts/embedded_app.html.erb#L11

**Comment by resistorsoftware** [comment]
I will use cssbundling, and probably stay away from Sprockets as that technology is most definitely DOA. I am guessing I can render whatever I want inside a card then, and am not limited in any ways!

**Comment by resistorsoftware** [comment]
OMG, this was so easy... cssbundling gem and boom. I have Tailwind in this project working... I am speechless.
