### ISSUE TITLE
Uploader Recommendation

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#22]
Polaris has no such thing as a file uploader. No React, or other bloatware. So what would be a good choice here for fil uploading? I imagine some nice generic Javascript coupled with a simple button to browse a file. Is there already some kind of Hotwire style file uploader out there? Looking for tips. I used uppy.io a bunch in previous Apps. I am guessing that will provide a nice path to working with Hotwire and Stimulus too. Or is there already something?

**Comment by dan-gamble** [comment]
You'd want to use the `Dropzone` Polaris component. I started it donkeys ago on https://github.com/baoagency/polaris_view_components but never finished it. I will see if I can get it sorted over Christmas!

**Comment by resistorsoftware** [comment]
Interesting. The App I am currently porting from Sinatra to this Rails Hotwire thing... is Dropzone. Wow. Synergy! 

At the same time, I see Rails people have a thing called Active Storage that probably works OK.. and with Stimulus might slot into working with Polaris too. I have never used Active Storage so I have no clue if it is any good or not, but I bet it is OK for the simple stuff. For me, I just need to store crap in S3, but it has to go direct from the browser to S3, which is painful sometimes. Something Uppy was good at!
