### ISSUE TITLE
Sitting on Homepage, and suddenly JWT fails

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#23]
If I sit on my homepage, the JWT token expires, and then the App ends up at the Splash page, and just sits there. What am I doing wrong? 

    [ShopifyApp::JWT] Failed to validate JWT: [JWT::ImmatureSignature] Signature nbf has not been reached
    11:42:33 web.1    | Started GET "/home" for 127.0.0.1 at 2022-01-10 11:42:33 -0500
    11:42:33 web.1    | Processing by HomeController#index as HTML
    11:42:33 web.1    | Redirected to https://someapp.test/?host=aG90d2lyZS1yZXNpc3Rvci5teXNob3BpZnkuY29tL2FkbWlu&return_to=%2Fhome&shop=hotwire-tester.myshopify.com
    11:42:33 web.1    | Filter chain halted as :redirect_to_splash_page rendered or redirected

The JS console shows that the App does ask for new tokens, and it gets a few... but then suddenly ends up with a 404 and the whole thing seems to die? 

`[shopify_app] Reusing token. Expires in: 6s application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11306:15
[Hotwire::Livereload] Files changed. Reloading.. hotwire-livereload.source.js:610
[shopify_app] Get new token application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11309:15
[Hotwire::Livereload] Files changed. Reloading.. hotwire-livereload.source.js:610
[shopify_app] Reusing token. Expires in: 35s application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11306:15
[Hotwire::Livereload] Files changed. Reloading.. hotwire-livereload.source.js:610
[shopify_app] Reusing token. Expires in: 29s application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11306:15
[Hotwire::Livereload] Files changed. Reloading.. hotwire-livereload.source.js:610
[shopify_app] Reusing token. Expires in: 8s application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11306:15
[Hotwire::Livereload] Files changed. Reloading.. hotwire-livereload.source.js:610
[shopify_app] Get new token application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js:11309:15
Source map error: Error: request failed with status 404
Resource URL: https://hotwire-tester.test/assets/application.debug-b39453633542784833fbad5a81513d190e96858c1a198af52c55fccc35b68a0e.js
Source Map URL: application.js-481834472df30e60f9211e88466db5ad137996479b4a2ee72d0fc392ed382def.map
`

**Comment by kirillplatonov** [comment]
It seems like a `shopify_app` gem issue. Check out this: https://github.com/Shopify/shopify_app/issues/1214

**Comment by resistorsoftware** [comment]
Oh. Wow. After reading that I am of the opinion then that the shopify_app gem is pretty bad at the basics. Blaming a timing issue in this age of everything having time from time servers, is really lame. People saying, OH, Shopify is hosted on Google Cloud, so use Google Cloud time servers reeks of desperation and naive acceptance of defeat.

**Comment by benbonnet** [comment]
@resistorsoftware lost hours on that one. can't agree more. shouldn't it be added to the troubleshooting page (https://github.com/Shopify/shopify_app/blob/main/docs/Troubleshooting.md) ?
