### ISSUE TITLE
App routing is acting up

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#24]
I just installed an app built on this hotwire sample, at heroku. The localhost version functions fine in my test development shop, but at heroku, it is a disaster. I am seeing a heroku "nothing here" screen. If I refresh, the App comes up, but does not last for long. What the heck it this? I have deployed hundreds of Apps to Heroku, and never has the default URL of the App brought up this screen. Anyone ever see this? 

[App image](https://www.evernote.com/l/ACdvDnMFu3ZJ_aFrbhdBvMXm-E-GUTiPe7kB/image.png)

**Comment by kirillplatonov** [comment]
Are you using a custom domain for this app on Heroku?

**Comment by resistorsoftware** [comment]
Nope. I have never experienced this. The App is installing, I can see a shop record in the DB at heroku. But no webhook fires there on App uninstall. Attempts to install hang at the splash screen, or I get that "nothing here" from heroku... gahhhhh something in the config is so botched.

**Comment by kirillplatonov** [comment]
This looks more like the Heroku configuration issue or Heroku outage. Not sure that it's related to app routing. Try reaching Heroku support.

**Comment by resistorsoftware** [comment]
Hilarious: https://youtu.be/zmlvM50MuYU

**Comment by resistorsoftware** [comment]
All I know is, watching the logs, the App is receiving and processing webhooks. So it is actually installed and working, even if the routing inside Shopify Admin is a bit whacked (at the moment?)... no idea how long this might last. Perhaps it is a temporary glitch in heroku.

**Comment by kirillplatonov** [comment]
This looks really weird. Do you have this code in SplashPageController?
https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/controllers/splash_page_controller.rb#L7
https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/controllers/splash_page_controller.rb#L15

**Comment by resistorsoftware** [comment]
Yes. It is pretty much the sample App as far as that aspect of it goes. All my work has been in other plumbing... I just write in a logo and card on the homepage... as far as changing the same App goes anyway.

**Comment by resistorsoftware** [comment]
I see heroku just returns 404.. like what????

<span class="message-body-wrapper">

GET | https://united-express.herokuapp.com/?hmac=9654ea787453aa0b15b04584dd8716b3ad43e4f96be40a293a881e8e383c8242&host=dW5pdGVkLXN1cGVybWFya2V0LWV4cHJlc3MubXlzaG9waWZ5LmNvbS9hZG1pbg&locale=en&session=bea1c91d3a36f13d96ddb9f70d06fa708c35274aadaa2e07e942429543d67378&shop=united-supermarket-express.myshopify.com&timestamp=1641844421
-- | --

404

So my App is there, and working, but according to Heroku it is 404... sigh.. great. 
</span>

**Comment by resistorsoftware** [comment]
And then wait a minute... refresh.. and voila.. it is back.. as if nothing happened. YoYoYo

**Comment by kirillplatonov** [comment]
Yeah, I got the same error it few times on this link. Really looks like a glitch on Heroku side.

**Comment by resistorsoftware** [comment]
I will leave the glitch alone then... it is not me going crazy.. it is heroku... which is understandable. It must be hard to ensure everything just always works.
