### ISSUE TITLE
After Direct Upload, this App dies in Safari

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#26]
I use Polaris View Components. I use Dropzone, and on the home page of this sample App, I upload a file direct to S3. Nothing crazy going on there. 

    <%= polaris_card(sectioned: true) do %>
        <%# With direct upload in ActiveStorage %>
        <%= form_with(model: @shop, builder: Polaris::FormBuilder) do |form| %>
          <%= form.polaris_dropzone :cost_price_upload, accept: "text/csv,.csv,application/vnd.ms-excel", multiple: false, direct_upload: true %>
          <%= polaris_button(submit: true, primary: true) { "upload" } %>
        <% end %>
      <% end %>

So Rails 7 processes all this, and I get a POST to home with the details of the upload. So I added a create to the home controller and it deals nicely with the upload. In Firefox, this works a peach. In Chrome it worked too.

In Safari however, this breaks. I have no idea why. I am not a Rails guy. 

The url in Safari is mangled as:    

     https://fizzbuzz.myshopify.com/admin/apps/rockemsockem-localhost/?return_to=%2Fhome%3Fshop%3Dfizzbuzz.myshopify.com

But in Firefox and Chrome, Rails ends up giving me:

    https://fizzbuzz.myshopify.com/admin/apps/rockemsockem-localhost/home

Which is great.

**Comment by kirillplatonov** [comment]
Are you using `turbo_redirect_to` method for the redirect? The standard `redirect_to` helper won't work in Safari for Shopify apps as it loses the JWT header during redirect.

Example of `turbo_redirect_to` usage: https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/controllers/messages_controller.rb#L6

**Comment by resistorsoftware** [comment]
Thank you for that. VERY KIND of you sir. I have no clue about anything TURBO, as for me, that represents some part of Rails I never worked with. So I will try harder to get up to speed on the advantages of this TURBO Business. 

Merci beaucoup!!!
