### ISSUE TITLE
Looking for an Explanation on Shop Create

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#28]
I have a development store with an App installed. A DB with the Shop table, etc. 

I replace that DB with one I pulled from the web, that does not have this store installed in it. 

I start the App in the development store, choosing from installed Apps listing, and find the store has now been installed in the DB and life goes on. **How come there was no dialog on the oAuth** here when the store was not found in the database? It is like this App just auto-installed itself with no issues. So weird.

**Comment by kirillplatonov** [comment]
This really doesn't belong to this repo. The OAuth is provided by shopify_app gem. You'd better ask it there: https://github.com/Shopify/shopify_app

**Comment by resistorsoftware** [comment]
I was just pointing out how your sample App exhibits that. Has nothing to do with oAuth. I understand that the App remained installed in the store as far Shopify was concerned, so a valid token for access was sent to the store, carry on.. I just think it is one of those weird behaviors. No biggy. I get it.
