### ISSUE TITLE
Issue with asset compiling

### ISSUE THREAD

**Issue by johnreaganmoore** [kirillplatonov/shopify-hotwire-sample#32]
Thanks for maintaining this project. I cloned it and followed the quick start but I am having trouble with the javascript compiling process. Here is the issue when I navigate to the embedded app. Any insight would be greatly appreciated. Thanks for your time.

bin/dev                         
15:48:12 web.1  | started with pid 78248
15:48:12 js.1   | started with pid 78249
15:48:12 js.1   | yarn run v1.22.10
15:48:12 js.1   | $ webpack --config webpack.config.js --watch
15:48:13 web.1  | => Booting Puma
15:48:13 web.1  | => Rails 6.1.5 application starting in development 
15:48:13 web.1  | => Run `bin/rails server --help` for more startup options
15:48:13 web.1  | Puma starting in single mode...
15:48:13 web.1  | * Puma version: 5.5.2 (ruby 3.0.3-p157) ("Zawgyi")
15:48:13 web.1  | *  Min threads: 5
15:48:13 web.1  | *  Max threads: 5
15:48:13 web.1  | *  Environment: development
15:48:13 web.1  | *          PID: 78248
15:48:13 web.1  | * Listening on http://127.0.0.1:3000
15:48:13 web.1  | * Listening on http://[::1]:3000
15:48:13 web.1  | Use Ctrl-C to stop
15:48:15 js.1   | asset application.js 239 KiB [compared for emit] [minimized] (name: application) 1 related asset
15:48:15 js.1   | orphan modules 265 KiB [orphan] 29 modules
15:48:15 js.1   | runtime modules 937 bytes 4 modules
15:48:15 js.1   | modules by path ./node_modules/@shopify/app-bridge/ 185 KiB 55 modules
15:48:15 js.1   | modules by path ./node_modules/@shopify/app-bridge-utils/ 27.6 KiB
15:48:15 js.1   |   modules by path ./node_modules/@shopify/app-bridge-utils/utilities/*.js 8.19 KiB 3 modules
15:48:15 js.1   |   modules by path ./node_modules/@shopify/app-bridge-utils/utilities/session-token/*.js 8.78 KiB 3 modules
15:48:15 js.1   |   modules by path ./node_modules/@shopify/app-bridge-utils/utilities/authorization-code/*.js 9.99 KiB 3 modules
15:48:15 js.1   |   ./node_modules/@shopify/app-bridge-utils/index.js 613 bytes [built] [code generated]
15:48:15 js.1   | ./app/javascript/application.js + 19 modules 249 KiB [built] [code generated]
15:48:15 js.1   | ./node_modules/@rails/actioncable/src/index.js + 8 modules 16.8 KiB [built] [code generated]
15:48:15 js.1   | webpack 5.70.0 compiled successfully in 1938 ms
15:48:18 web.1  | Started GET "/cable" for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:18 -0400
15:48:18 web.1  | Cannot render console from 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912! Allowed networks: 127.0.0.0/127.255.255.255, ::1
15:48:18 web.1  |    (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
15:48:18 web.1  | Started GET "/cable/" [WebSocket] for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:18 -0400
15:48:18 web.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
15:48:18 web.1  | Hotwire::Livereload::ReloadChannel is transmitting the subscription confirmation
15:48:18 web.1  | Hotwire::Livereload::ReloadChannel is streaming from hotwire-reload
15:48:22 web.1  | Started GET "/?hmac=d34100f09635c27208ca594647e0cde3959d447e4f2de21cbcd27b03e5eadc16&host=YmVhdXR5LW1lZHMtZGV2Lm15c2hvcGlmeS5jb20vYWRtaW4&shop=beauty-meds-dev.myshopify.com&timestamp=1648149562" for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:22 -0400
15:48:22 web.1  | Cannot render console from 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912! Allowed networks: 127.0.0.0/127.255.255.255, ::1
15:48:22 web.1  | Processing by SplashPageController#index as HTML
15:48:22 web.1  |   Parameters: {"hmac"=>"d34100f09635c27208ca594647e0cde3959d447e4f2de21cbcd27b03e5eadc16", "host"=>"YmVhdXR5LW1lZHMtZGV2Lm15c2hvcGlmeS5jb20vYWRtaW4", "shop"=>"beauty-meds-dev.myshopify.com", "timestamp"=>"1648149562"}
15:48:22 web.1  |   Shop Load (1.1ms)  SELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "beauty-meds-dev.myshopify.com"], ["LIMIT", 1]]
15:48:22 web.1  |   ↳ app/middleware/app_bridge_middleware.rb:15:in `call'
15:48:22 web.1  |   CACHE Shop Load (0.0ms)  SELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "beauty-meds-dev.myshopify.com"], ["LIMIT", 1]]
15:48:22 web.1  |   ↳ app/middleware/app_bridge_middleware.rb:15:in `call'
15:48:22 web.1  |   CACHE Shop Load (0.0ms)  SELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "beauty-meds-dev.myshopify.com"], ["LIMIT", 1]]
15:48:22 web.1  |   ↳ app/controllers/splash_page_controller.rb:16:in `index'
15:48:22 web.1  |   Rendering layout layouts/embedded_app.html.erb
15:48:22 web.1  |   Rendering splash_page/index.html.erb within layouts/embedded_app
15:48:22 web.1  |   Rendered splash_page/index.html.erb within layouts/embedded_app (Duration: 0.7ms | Allocations: 334)
15:48:22 web.1  |   Rendered layouts/_flash_messages.html.erb (Duration: 0.6ms | Allocations: 335)
15:48:22 web.1  |   Rendered layout layouts/embedded_app.html.erb (Duration: 38.3ms | Allocations: 31513)
15:48:22 web.1  | Completed 200 OK in 472ms (Views: 40.6ms | ActiveRecord: 15.8ms | Allocations: 44837)
15:48:22 web.1  | 
15:48:22 web.1  | 
15:48:23 web.1  | Finished "/cable/" [WebSocket] for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:23 -0400
15:48:23 web.1  | Hotwire::Livereload::ReloadChannel stopped streaming from hotwire-reload
15:48:23 web.1  |   
15:48:23 web.1  | ActionController::RoutingError (No route matches [GET] "/assets/application.js-4ef2f7fdf41f55832ffd057d21e954f6c254c581886848ccc2018bd245426c08.map"):
15:48:23 web.1  |   
15:48:23 web.1  | Started GET "/cable" for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:23 -0400
15:48:23 web.1  | Cannot render console from 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912! Allowed networks: 127.0.0.0/127.255.255.255, ::1
15:48:23 web.1  | Started GET "/cable/" [WebSocket] for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:23 -0400
15:48:23 web.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
15:48:24 web.1  | Hotwire::Livereload::ReloadChannel is transmitting the subscription confirmation
15:48:24 web.1  | Hotwire::Livereload::ReloadChannel is streaming from hotwire-reload
15:48:25 web.1  | Started GET "/cable" for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:25 -0400
15:48:25 web.1  | Cannot render console from 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912! Allowed networks: 127.0.0.0/127.255.255.255, ::1
15:48:25 web.1  | Started GET "/cable/" [WebSocket] for 2603:3007:1c01:6d00:c4f3:f254:f1b1:c912 at 2022-03-24 15:48:25 -0400
15:48:25 web.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
15:48:25 web.1  | Hotwire::Livereload::ReloadChannel is transmitting the subscription confirmation
15:48:25 web.1  | Hotwire::Livereload::ReloadChannel is streaming from hotwire-reload

**Comment by resistorsoftware** [comment]
I know next to nothing, but I do know, webpack is one of the worst tools inflicted on devs ever. You do not need webpack. If you look at the package.json, it uses the amazing esbuild. It is FAST. 

"scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds"
  },

If you have sprockets-rails in your gem you get all your assets working perfect with this project. I am not sure why that gem is missing. You can skip it if you use importmaps and figure out your own asset pipeline... but for me... I get all my JS and CSS perfect with this repo as is... 

Maybe try killing webpack and going with the esbuild.
