### ISSUE TITLE
Include GraphQL

### ISSUE THREAD

**Issue by Kurbm** [kirillplatonov/shopify-hotwire-sample#38]
Hey @kirillplatonov 

I would like to implement your graphql example into the hotwire sample (https://github.com/kirillplatonov/shopify_graphql).

But I'm not so sure how to actually do it. 

I already installed your gem and added fields and a get query to a graphql folder. For now a super simple one

**Product fields**

`
module ShopifyGraphql
  class ProductFields
    FRAGMENT = <<~GRAPHQL
      fragment ProductFields on Product {
        id
        title
      }
    GRAPHQL

    def self.parse(data)
      OpenStruct.new(
        id: data.id,
        title: data.title
      )
    end
  end
end
`

**Get Products**

`module ShopifyGraphql
  class GetProducts
    include Query

    QUERY = <<~GRAPHQL
      #{ProductFields::FRAGMENT}
      query{
        products(first: 10, query: "title:*rolf*") {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    GRAPHQL

    def call
      response = execute(QUERY)
      response.data = parse_data(response.data)
      response
    end

    private

    def parse_data(data)
      unless data.node
        raise ResourceNotFound.new(200, "Products not found")
      end

      OpenStruct.new(
        products: ProductFields.parse(data.node),
      )
    end
  end
end
`

But now I'm a bit stuck, how I actually could run this query from a controller. E.g. someone would search for a partial product title in a search form and should see the result than as a list.

Could you may help me out, to figure out, where I would need to call the function?

**Potential call function**

` products = GetProducts.call.data
   @title = products.title`
   
   Thanks and best,
   Kevin

**Comment by Kurbm** [comment]
Amazing. Thanks a lot.

**Comment by kieranmasterton** [comment]
@kirillplatonov I was using your (brilliant) `shopify_graphql` gem with the previous incarnation of this sample but the update to use `shopify_app` 21.2 and `shopify_api` 12.2 has meant they're incompatible. Are you planning to update the `shopify_graphql` or do Shopify's changes to their API gem prevent you from making the two projects compatible currently?

**Comment by kirillplatonov** [comment]
@kieranmasterton yeah, I will be looking at compatibility issues this week

**Comment by Kurbm** [comment]
Hey @kirillplatonov,

I just played around a bit with your graphql gem.

One question, I tried to create a simple query in the home controller, just to see if I'm able to get it to work.

```
def index
		shop_origin = current_shopify_domain
    shop = Shop.find_by(shopify_domain: current_shopify_domain)
		shop.with_shopify_session do
			# your calls to graphql
			query = <<~QUERY
				query {
					products(first: 10, reverse: true) {
						edges {
							node {
								id
								title
								handle
								resourcePublicationOnCurrentPublication {
									publication {
										name
										id
									}
									publishDate
									isPublished
								}
							}
						}
					}
				}
			QUERY
			response = ShopifyGraphql.execute(query)
			response.data = parse_data(response.data)
			response
		end
end
```

I'm getting now the error: uninitialized constant ShopifyAPI::Base

I have added all the files, you have provided in your shopify_graphql gem. Just needed to make one change to your code part in the 

```
ShopifyGraphql.configure do |config|
  # Webhooks
  webhooks_prefix = "https://#{Rails.configuration.app_host}/graphql_webhooks"
  config.webhook_jobs_namespace = 'shopify/webhooks'
  config.webhook_enabled_environments = ['production']
  config.webhooks = [
    { topic: 'SHOP_UPDATE', address: "#{webhooks_prefix}/shop_update" },
    { topic: 'APP_SUBSCRIPTIONS_UPDATE', address: "#{webhooks_prefix}/app_subscriptions_update" },
    { topic: 'APP_UNINSTALLED', address: "#{webhooks_prefix}/app_uninstalled" },
  ]
end
```

to the config/initializers/shopify_app.rb the app crashes on launch. I needed to change the  "https://#{Rails.configuration.app_host}/graphql_webhooks" to "#{ENV['HOST']}/graphql_webhooks"

Just to see, if I'm able to at least get the products. The main reason for this is, that Shopify requires everyone to update to the latest app bridge version and there is no real progress from Shopify's side, with your pull request with the full page redirect. Therefore, I need to be able to create subscription charges. Else I can not deploy the updated app version of my app.

Do you have any idea, how I can call graphql queries from the home controller? So I would be able to create and find subscription charges if customers launch the app and land on the home path.

**Comment by kirillplatonov** [comment]
@Kurbm I added ShopifyAPI 10+ support to ShopifyGraphql gem but didn't published new release yet. You can install it from Github for now:
```
gem "shopify_graphql", github: "kirillplatonov/shopify_graphql", branch: "main"
```

After that, the error should disappear. Also, the gem includes built-in mutations for subscription. For example:
```rb
response = CreateRecurringSubscription.call(
  name: "Plan Name",
  price: 10,
  return_url: "RETURN URL",
  trial_days: 3,
  test: true,
).data
confirmation_url = response.confirmation_url
shopify_subscription = response.subscription
```

**Comment by Kurbm** [comment]
Hey,

worked. Thanks.
