### ISSUE TITLE
Adding the new Shopify frame-ancestor policy

### ISSUE THREAD

**Issue by Kurbm** [kirillplatonov/shopify-hotwire-sample#44]
Hey @kirillplatonov 

Shopify now enforces the frame-ancestor policy for new apps (frame-ancestors https://[shop].[myshopify.com](http://myshopify.com/) https://admin.shopify.com/). Do you have an idea, how it needs to get implemented?

I'm just playing around with the following

Based on the CSP from Shopify's JWT Sample app: https://github.com/Shopify/turbolinks-jwt-sample-app

`
initial_frame_ancestors = [:https, "*.myshopify.com", "admin.shopify.com"]

def current_domain
  @current_domain ||= (params[:shop] && ShopifyApp::Utils.sanitize_shop_domain(params[:shop])) ||
    request.env["jwt.shopify_domain"] ||
    session[:shopify_domain]
end

frame_ancestors = lambda { current_domain ? [ current_domain, "admin.shopify.com" ] : initial_frame_ancestors }

Rails.application.config.content_security_policy do |policy|
  policy.default_src(:https, :self)
  policy.style_src(:https, "'unsafe-inline'", "cdn.shopifycloud.com")
  policy.script_src(:https, "'unsafe-inline'", "cdn.shopifycloud.com")
  policy.img_src(:self, :https, :data, "cdn.shopifycloud.com")
  policy.upgrade_insecure_requests(true)
  policy.frame_ancestors(frame_ancestors)
end
`

This leads now to the problem that the Recurring Charge Worklow with a full-page redirect does not work anymore.

Best,
Kevin

**Comment by resistorsoftware** [comment]
I am not even using the Recurring Charge Workflow, and this App gets blocked with:

`App must set security headers to protect against clickjacking.
There was an error opening your app in the Shopify admin. Your embedded app is loading an invalid URL`

So this is super annoying and so far, I have no idea how or why to clean that up. It was hard enough getting the original CSP to work as Shopify did nothing for almost a year about it... I hope a fix comes quickly!

**Comment by Kurbm** [comment]
@resistorsoftware I think it gets automatically added with Shopify App V20. But not 100% sure. I think I have read it somewhere :)

**Comment by resistorsoftware** [comment]
Anyway @Kurbm did you get this particular aspect of the use of this repo fixed? I am curious as it is currently blocking me on an install. If you did fix it, can you just point out the obvious to me.

**Comment by Kurbm** [comment]
@resistorsoftware not yet.

**Comment by resistorsoftware** [comment]
I just had an App pass review, with this repo as the basis, with no upgrade to API 10+. My CSP policy was in fact fine with Shopify, it was their test robot throwing false positives on CSP violations. 

I will be super happy when we can use this Repo with the newer API and oAuth patterns, knowing that should be reliable for some time to come. A little pain now, a lot of no pain later. Here is hoping anyway.
