### ISSUE TITLE
How to use this App with the new CSP? 

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#45]
I am experiencing Shopify now rejecting this App pattern.

```
App must set security headers to protect against clickjacking.
There was an error opening your app in the Shopify admin. Your embedded app is loading an invalid URL
```

I am loading the policy for CSP just fine, and up until a few days ago, it worked fine.. but now Shopify rejects the App. Anybody have any quick and dirty fixes for this? 

The App Listing security App is puking not on the frame ancestors, but a call to the main index page. So the message is, you cannot submit this App for review, till this is fixed. I am thinking that is because the splash page has no CSP, that is the culprit? Do I just need to add the CSP to the splash controller to make Shopify happy?

**Comment by kirillplatonov** [comment]
I'm preparing an upgrade to ShopifyApp v20 (https://github.com/kirillplatonov/shopify-hotwire-sample/pull/42). I hope it will resolve this issue as ShopifyApp includes built-in configuration for CSP.

**Comment by scart88** [comment]
This has been working for us.

`config/initializers/content_security_policy.rb`
```ruby
  Rails.application.config.content_security_policy do |policy|
    policy.frame_ancestors :self, 'https://*.myshopify.com', "https://admin.shopify.com"
  end
```
