### ISSUE TITLE
Find live theme without theme.all api call

### ISSUE THREAD

**Issue by Kurbm** [kirillplatonov/shopify-hotwire-sample#50]
Hey,

@kirillplatonov I have implemented the Theme versioning check of yours in my new app. (https://kirillplatonov.com/posts/detecting_shopify_theme_version/)

This is super helpful and works very well in the "old hotwire sample" of yours.

Now with the new Shopify App v21 theme.find and theme.all as methods are missing and can not be used anymore.

Do you have an idea, how to build a workaround for the versioning. I have opened an issue in the shopify ruby API repository as well (https://github.com/Shopify/shopify-api-ruby/issues/1060)

And also thanks a lot for your work with the polaris view components and this hotwire sample.

It is just awesome.

Best,
Kevin

**Comment by Kurbm** [comment]
@kirillplatonov looks like that Theme methods do not work anymore with the new shopify API and gem.

https://kirillplatonov.com/posts/detecting_shopify_theme_version/
-> so this will not work anymore with this updated gem and API version

**Comment by kirillplatonov** [comment]
Hey Kevin,

Yeah, Shopify 10 contains quite a lot of breaking changes. I will prepare an update for my apps and publish it in the blog.

**Comment by kirillplatonov** [comment]
@Kurbm I added updated code with ShopifyAPI 10+ support to article:
https://kirillplatonov.com/posts/detecting_shopify_theme_version/
