### ISSUE TITLE
What do you think about this? 

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#51]
The Shopify App template for Ruby Apps is interesting. Not saying I like it, but the arrangement is interesting. Would it be worth investing the time to take this particular project in that direction? 

https://github.com/Shopify/shopify-app-template-ruby#setting-up-your-rails-app

**Comment by kirillplatonov** [comment]
I like it a lot. It's very nicely integrated with Shopify CLI 3.0. And it's very easy to spin a new app using it. It would be awesome to have a hotwire template for Shopify CLI 3.0 based on this sample repo and use it like this:
```
yarn create @shopify/app --template=hotwire
```

I will ask someone from the Shopify CLI team if they could add support for custom templates.

**Comment by resistorsoftware** [comment]
The two improvements I asked for were to have named tunnels (which they gave me a recipe for!!) and I was always getting tripped up by the fact the Rails App lived in /web and so often I would run a command like **rails c** for a console and have that bomb out. Again, they offered up a kind of solution in a batched command, but still. If we could have the Hotwire App in there instead of the React one, it would be super, as it would be the best of both worlds of CLI v3 and Hotwire / Polaris View Components.

**Comment by kirillplatonov** [comment]
It turns out we can use GitHub URLs as a template:
```bash
yarn create @shopify/app --template=https://github.com/kirillplatonov/shopify-hotwire-sample
```

Now, all we need is to update the sample to support the new app structure and CLI 3.

**Comment by resistorsoftware** [comment]
I have used a template in the past, but it has been awhile. One has to do as much work keeping the template updated as there are new projects to spawn from the template sometimes!

**Comment by resistorsoftware** [comment]
I am wanting to now migrate an App using this repo to CLI3. I am thinking it will be fairly easy, but of course, I cannot tell till I do it. Shopify documentation is a little fuzzy on some aspects. This App for example, not being API driven, has no front-end or need of that distinction, so I am hoping I can just cram the whole thing into /web, and move my extensions out of the Rails app an under the projects /extensions, then fiddle with the actual CLI commands and their TOML and be done.

**Comment by kirillplatonov** [comment]
Closing in favor of #63
