### ISSUE TITLE
Brief list of things

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#55]
As you point out, for Heroku, a HOST entry is needed with the https://someapp.herokuapp.com

I am also finding the default install is not as straightforward as the now-defunct READme file indicates. Some things I am always doing.

- updating to use standard and rubocops
- getting rid of error with older bundler, and updating Thor and Bootsnap due to deprecation I dislike seeing
- for some reason, I am having to do a JS build, ie) yarn add esbuild to get thing working on that front. 
- I am adding  tunnel entry to my Procfile.dev to ngrok so I can my puma-dev and named tunnels

    tunnel: ngrok http 3154 --subdomain=foo-man-chu --log=stdout --log-level=info

- I am having to go into database.yml and make up decent DBs, always changing production to DATABASE_URL
- adding ngrok info and redis info to the .env 

with all that out of the way, it does seem to go without too much trouble!

**Comment by kirillplatonov** [comment]
I will appreciate PRs to improve the default setup
