### ISSUE TITLE
oAuth Flow Question

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#58]
I am seeing Page Not Found problems when Stores try and connect. My underlying database with all the stores was zeroed out, but about twenty stores had API keys for the App. So the App remained installed inside Shopify, showing these twenty installs. 

So when one of these stores tries to connect to the App, it errors out, and says Page not Found. 

What should happen instead, is the App recognizes that the incoming shopify_domain has no record in the DB, so it should initiate an oAuth flow to re-install that store in the App. 

Any clue as to why this App fails at that? It my only guess as to why I am seeing this Page Not Found error.

**Comment by kirillplatonov** [comment]
Do you have the code for triggering the OAuth check in SpashPageController: https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/controllers/splash_page_controller.rb#L18
Without this, the app won't fetch new token.

**Comment by resistorsoftware** [comment]
I have slightly different code. Probably from an older version of this repo:
    
    def index 
        @shop_origin = current_shopify_domain

        # required to trigger OAuth token check
        shop = Shop.find_by(shopify_domain: current_shopify_domain)
        shop.with_shopify_session do
          ShopifyAPI::Shop.current
       end
    end

**Comment by uurcank** [comment]
@resistorsoftware use shopify_app gem from master and [this issue is fixed there](https://github.com/Shopify/shopify_app/commit/c3e89a93ca507a411ee99c4515f0e39e991577e0)

**Comment by resistorsoftware** [comment]
Thanks, my lockfile shows I am using: v21.3.1 so hopefully this resolves that issue.
