### ISSUE TITLE
admin.shopify.com issue, template no longer works

### ISSUE THREAD

**Issue by uurcank** [kirillplatonov/shopify-hotwire-sample#59]
The template does not work with new stores that loads under admin.shopify.com @kirillplatonov 

Most likely due to the middleware, which sets a host parameter with myshopify.com structure.

**Comment by uurcank** [comment]
[Pushed a fix here](https://github.com/kirillplatonov/shopify-hotwire-sample/pull/60)

**Comment by kirillplatonov** [comment]
Thanks, merged
