### ISSUE TITLE
Using with CLI 3

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#61]
I need to port this App to CLI 3 to use it with an extension as CLI 2 is soon to be DOA. Yay. 

Can anyone explain what the shopify.app.toml settings should be? My attempt failed when I did the simple migration recipe they suggested. 

- moved the app from root to web/ directory and made an extensions/ directory, so far so good.
- created a package.json with the @shopify/cli and @shopify/app dependencies, again, so far, so good
- created a shopify.app.toml in the root to satisfy the CLI. 
- created a shopify.web.toml in the web directory, as type *frontend* 

Now running the CLI, with *yarn dev* should boot up the App in a tunnel, and away we go, but instead, the CLI just dies and returns to the shell after apparently booting everything up. I wish this CLI was not a thing, but I need to provide extensions now, and while I can always start from scratch with the Shopify App as they dump it out in their template, it is that crappy React thing I dislike and not the nicer Polaris view components like this one.

Anyone have any experience with this migration they can add for me? I am not sure why the CLI fails to boot up the App.

**Comment by BaggioGiacomo** [comment]
Have you found out @resistorsoftware? We're in the same boat at the moment

**Comment by resistorsoftware** [comment]
@BaggioGiacomo I do know that I raised this issue before I figure it out I guess. There actually is no issue. CLI 3 is not the problem anyway. My recipe for success is to spawn an App with CLI 3, then I just remove the entire Shopify App Rails from the project ( the /web stuff), then I insert this Rails App instead. I then manually adjust things as if I am working on this Rails App without CLI 3, and it just works fine. If we could all collectively get our heads around fixing up this repo to be more compatible with the latest, it would save a lot of tweaking, but honestly, within 10 minutes, I can manually have it all done and working just fine, so I am not too concerned. Plus, I use this repo in my own ways, not necessarily same as someone else might. 

Anyway, just deploy this to the /web, and test as normal. Nothing has changed. It is a Rails App. And there is zero reason to bypass oAuth. That is never a concern AFAIK. It just works, so my bypass it?

**Comment by BaggioGiacomo** [comment]
Only the backend is in Rails, the frontend (of the embedded app) is made in React
This is the template: https://github.com/Shopify/shopify-app-template-ruby

**Comment by BaggioGiacomo** [comment]
Because i've found [this article](https://kirillplatonov.com/posts/testing-shopify-apps-in-rails/) while trying to understand how can I implement system tests. Thanks anyway!

**Comment by resistorsoftware** [comment]
Ahhh! OK... well like I said, this App is nothing but a normal Rails App, so tests work as per any usual Rails App.
