### ISSUE TITLE
Got it working with CLI 3

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#63]
Just a FYI, good news kind of thing. I was able to get the hotwire App working with a CLI 3 App deploy with the TOML files. I am adding the extensions and with that, I will be happy to maintain things moving forward. It was a struggle, and I still have not been able to do it manually, but perhaps with time I will figure it out. 

TL:DR; I had to create a CLI App and let the tool do all the work. I erased the web/ directory, and replaced that with the Hotwire App. It worked! When I did a manual conversion of a Hotwire App to CLI 3 pattern, it failed. No idea why...

**Comment by kirillplatonov** [comment]
This is great news. I think it makes perfect sense to convert this repo for CLI 3.0. 

One concern I have is deployment to Heroku. Heroku expects that the app will be stored in root of the repo but with CLI 3.0 it will be `web` subfolder. Shopify suggests deploying the app via Docker containers but I'm not a fan of this as it will most likely introduce some new challenges. Hopefully, we can find a way to deploy from the subfolder on Heroku. Alternatively, Render supports deployments from subfolders out of the box.

**Comment by resistorsoftware** [comment]
I thought of that. Here is what I do at the moment. My web/ directory is the entire App, both localhost and production. Same as before. So if I was to inform this directory as my remote for heroku, a git push from here would work identical to the usual pattern. What happens if I now backout one level, to the root? I am faced with nothing of much importance except whoa!! The extensions are there now! Oopsie. Shopify needs the extension code too when I deploy to heroku. So now I am stuck where you mention. How to deploy this scenario?

I am not a fan of Docker either as it is just another level of abstraction that would need maintenance over time. But it may be the only way. I have one working Docker Rails install pattern I can try. If it works (I have not used it recently) I may try it with one of these new CLI 3 Apps. 

I really don't want to move to a new service. Heroku is just too good even with all the problems of the real world and Salesforce, etc.

**Comment by Kurbm** [comment]
@resistorsoftware just trying to get a first version running as you kind of subscribed here.

So what I have done so far, is creating an app via cli (yarn create @shopify/app).

Deleted all content in the web folder, but kept the web folder. Then added all files from this repo into the web folder.

I can create extensions via CLI3. So that looks like it is working.

If I now want to install the app in a test store, it tells me. That there is no page address.

"There's no page at this address
Check the URL and try again, or use the search bar to find what you need."

Running the bin/dev and bin/tunnel from the web folder.

Did you issues like this?

**Comment by resistorsoftware** [comment]
I added a shopify.web.toml of type "frontend" and set that to run my foreman command, which uses my Procfile.dev. 

So when I want to install in a test store, I just use the yarn run dev command, which fires up the Rails App as per how it all used to work without CLI3. I use puma-dev for named tunnels. So that works. I am betting your API keypair is just not setup to talk to your App running on your localhost, hence the no page address thing. My dotenv file helps out here somewhat. 

    SHOPIFY_API_KEY=58ae7450224edc26af20d65321ddxxxx
    SHOPIFY_SECRET_KEY=b4deccd5103cddb20e5b2e62fae2xxxx
    PORT=3201
    CONFIG=config/puma.rb
    REDIS_URL=redis://localhost:6379
    HOST=https://cold-beer.test

So when I fire up the CLI 3 version, and I click on my tunnel, everything just works, as I set my tunnels in my API set up in Shopify to point to cold-beer.test.

**Comment by Kurbm** [comment]
@resistorsoftware No. This is, as far as I can see, not related to the API settings. 

I just have seen, if you install the app "manually" over the partners dashboard, the host tunnel is missing the slug login. 

If you grab the URL, before it redirects and you would add the slug login, the app gets installed normally.

Just one interesting thing, that it gets a "forced" redirect to the old shopify URL structure. If you just use the normal repository as it is currently, you would not get the forced redired.

**Comment by resistorsoftware** [comment]
I can't help here obviously. I hope you get it working and let us know what you had to do!

**Comment by Kurbm** [comment]
Thanks anyway. I will try to find a way and let you know.

**Comment by resistorsoftware** [comment]
Kirill did say today that the middleware was not working for the new admin.shopify.com so maybe that is the problem.

**Comment by Kurbm** [comment]
@resistorsoftware actually installing works again. A bit like magic.😅 

So as it looks like, as you mentioned, you can replace the whole content in the web folder with this repo app and then run bin/dev from the web folder. Same for the cloudflare bin/tunnel. 

App installs normally and works as well. Only the strange thing with the "admin URL force redirect", but this could be connected to the middleware issue.

I did not test this yet for production, but working on a new app, which I try to launch soon, with this approach. I will let you know, if Shopify complains or not.

Extensions can be easily generate and pushed with the standard shopify cli3 commands, so this should work as well.

Not sure, if the shopify.web.toml for frontend and backed is needed at all.

**Comment by resistorsoftware** [comment]
@kurbm I have a shopify.app.toml that contains the name of my App in the root, and then in web the needed shopify.web.toml with the instructions on how to run the App. Because I am used to using a Procfile.dev with my commands, and tunnels, with foreman, I just use that as my command for the yarn dev... works perfect!
