### ISSUE TITLE
Missing Host 

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#64]
Typically, what might cause this App to all of a sudden start failing with this? 

Started GET "/?host=undefined&return_to=%2Fhome%3Fshop%3Dfud.myshopify.com%26host%3Dundefined&shop=hotwire-resistor.myshopify.com" for 127.0.0.1 at 2023-01-11 19:36:35 -0500

Why would host be undefined? 

If I call the App from the CLI, that URL has a host. So all is good. Then I just edit say a CSS setting. So hotwire reload kicks in, and next thing you know, the App is stuck at the Splash page with no host.. spinning forever.. that is annoying. I am curious as to what is causing the host to become zapped.

If I hack the middleware that is used to set the host if it is missing, I add the check if it is there, but set to "undefined" and fix it there. But I should not be seeing a host of undefined ever... what could be generating that? When Hotwire Reload issues the GET '/' after a recompile of an asset, this is when host is set to undefined. 

Example console run, we note undefined at first, but the middleware hack fixes it... 

    Finished "/cable" [WebSocket] for 127.0.0.1 at 2023-01-11 19:53:51 -0500
    Hotwire::Livereload::ReloadChannel stopped streaming from hotwire-reload
    Started GET "/cable" for 127.0.0.1 at 2023-01-11 19:53:51 -0500
    Started GET "/cable" [WebSocket] for 127.0.0.1 at 2023-01-11 19:53:51 -0500
    Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
    Started GET "/home?shop=fud.myshopify.com&host=undefined" for 127.0.0.1 at 2023-01-11 19:53:52 -0500
    Started GET "/cable" for 127.0.0.1 at 2023-01-11 19:53:52 -0500
    Hotwire::Livereload::ReloadChannel is transmitting the subscription confirmation
    Hotwire::Livereload::ReloadChannel is streaming from hotwire-reload
    Processing by HomeController#index as HTML
    Parameters: {"shop"=>"fud.myshopify.com", "host"=>"aG90d2lyZS1yZXNpc3Rvci5teXNob3BpZnkuY29tL2FfbWlu"}

**Comment by vasaf** [comment]
Is the store using the new admin.shopify.com domain?

**Comment by resistorsoftware** [comment]
Should not matter if it is, there is a line of code in the middleware to detect that. But ya.. somehow, undefined is getting in there!

**Comment by vasaf** [comment]
> I'm afraid the middleware is not working properly on the new admin.shopify.com domain. The app is called within an iframe so we can't detect if it's a new domain from a URL:
> 
> ```ruby
> if request.url.include?("admin.shopify.com")
> ```
> 
> I will publish a new workaround for setting host that I'm using in my apps.

Setting and saving the domain to the shop from the `splash_page_controller.rb` works for me.

```
def index
    @shop_origin = current_shopify_domain

    shop.with_shopify_session do
      ShopifyAPI::Shop.all.first
    end
    if request.params.has_key?("host")
      host = Base64.urlsafe_decode64(request.params["host"])
      unless shop.shopify_host == host
        shop.update_attribute(:shopify_host, host)
      end
    end
  end
```

**Comment by resistorsoftware** [comment]
Damn, that's heavy! Heavy metal baby. Saving a param in the DB!

**Comment by vasaf** [comment]
The bandaid that keeps on giving

**Comment by resistorsoftware** [comment]
I am assuming that you use this parameter too. Do you have a preferred methodology for using what you saved?

**Comment by resistorsoftware** [comment]
> > I'm afraid the middleware is not working properly on the new admin.shopify.com domain. The app is called within an iframe so we can't detect if it's a new domain from a URL:
> > ```ruby
> > if request.url.include?("admin.shopify.com")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will publish a new workaround for setting host that I'm using in my apps.
> 
> Setting and saving the domain to the shop from the `splash_page_controller.rb` works for me.
> 
> ```
> def index
>   @shop_origin = current_shopify_domain
> 
>   shop = Shop.find_by(shopify_domain: current_shopify_domain)
>   shop.with_shopify_session do
>     ShopifyAPI::Shop.all.first
>   end
>   if request.params.has_key?("host")
>     host = Base64.urlsafe_decode64(request.params["host"])
>     unless shop.shopify_host == host
>       shop.update_attribute(:shopify_host, host)
>     end
>   end
> end
> ```

How does **shop.shopify_host** get used in your version of the App?

**Comment by uurcank** [comment]
have you tried somethig like this @resistorsoftware 

```
if request.params.has_key?("shop") && !request.params.has_key?("host")
shop = request.params["shop"]
if request.params["host"] == 'undefined' 
   host = Base64.urlsafe_encode64("admin.shopify.com/store/#{shop}", padding: false)
else
      if request.url.include?("admin.shopify.com")
        shop = shop.gsub(".myshopify.com", "").gsub(".myshopify.io", "")
        host = Base64.urlsafe_encode64("admin.shopify.com/store/#{shop}", padding: false)
      else
         host = Base64.urlsafe_encode64("#{shop}/admin", padding: false)
      end
end
end
```

**Comment by resistorsoftware** [comment]
@uurcank if you read @kirillplatonov missive up there, he points out that you cannot rely on the request to get the correct URL in the iframe, and @vasaf implies saving the host when the Splash controller gets hit, but does not show how to efficiently use that value, assuming you assign the host to the shop. So that remains the question.

**Comment by uurcank** [comment]
@resistorsoftware it sounds like an issue for development only. For some reason hotwire reload gets the URL before middleware. 

In development, you can default to middleware to admin.shopify.com or myshopify.com

```
if Rails.env.development? 
 ...
end 

```

Shopify will probably switch to admin.shopify.com for all accounts very soon, at that point middleware can default to admin.shopify.com for all calls.

**Comment by resistorsoftware** [comment]
@uurcank well it is not limited to the development phase AFAIK, because when you have Apps in production and you don't know which way Shopify is going to go with the App... you should have both options covered.

**Comment by uurcank** [comment]
@resistorsoftware true but I am not sure about this one. There is no hotwire-reload in production.

**Comment by resistorsoftware** [comment]
@uurcank Misunderstanding! Regardless of the Hotwire Reload, I am dwelling on the fact the host parameter is not being set proprerly for whatever reason. I agree with you on the fact reload is only a development issue, but host setting is universal and appears to be muffed in certain combinations of Shopify and this App!

**Comment by Kurbm** [comment]
Leads actually to additional problems, I guess. If you try doing fetch requests via stimulus / request.js it leads to a 401 unauthorized error.

**Comment by resistorsoftware** [comment]
@Kurbm that should in fact never be a problem as we have getSessionToken and make JWT calls... so 401 is some other kind of glitch, perhaps from something misconfigured in the App... I am not getting any issues with my stimulus requests!! They all just work...

**Comment by Kurbm** [comment]
@resistorsoftware ok, that it could be a different "glitch". All this has worked absolutely perfectly until today. So yesterday evening everything worked. Today the error appears. Maybe it disappears automatically in a few hours.

**Comment by resistorsoftware** [comment]
Usually when this happens to me, it is because I messed with something fundamental, and forgot. Then I am convinced the whole thing is busted, when really, it was a misconfiguration. So yes, I am betting if you reversed your commits back to where it worked, you'd expose the change that causes this glitch for you!

**Comment by uurcank** [comment]
@resistorsoftware i still cannot see why this would be a problem in production, however you can definitely add a column to your database and just pass it to [application controller](https://github.com/kirillplatonov/shopify-hotwire-sample/blob/7d060089b1759dd16fa990496e42d28355a4b3db/app/controllers/application_controller.rb#L20). That's a valid alternative and a good backup plan.

One other option could be checking for undefined host parameter in Splash controller. If undefined, you can redirect user to oauth flow or just pass your database value. 

For development environment, just use one of the shopify domains as default.

**Comment by resistorsoftware** [comment]
You only get a host out of a shop when you know the shop. So if we notice the host is nil, we have to assume the params for shop are there. otherwise, chaos! So assuming we know the params[:shop] exists, and host is nil, we now have to set the host to be whatever the value is from the database. And if the database does not have the value for host, we're screwed.

So ya.. awesome

**Comment by Kurbm** [comment]
> Usually when this happens to me, it is because I messed with something fundamental, and forgot. Then I am convinced the whole thing is busted, when really, it was a misconfiguration. So yes, I am betting if you reversed your commits back to where it worked, you'd expose the change that causes this glitch for you!

@resistorsoftware you were absolutely write. Messed something up in my controller.

**Comment by scart88** [comment]
Shopify is using Base64.strict_encode64

```ruby
@host = "some-shopify-store.myshopify.com/admin"
@encoded_host = Base64.strict_encode64(@host)
```

As seen here
https://github.com/Shopify/shopify-api-ruby/blob/main/test/auth_test.rb#L11

Also, I spot the `ENV['HOST']` in the `boot.rb` in their example
https://github.com/Shopify/shopify-app-template-ruby/blob/main/web/config/boot.rb#L4
