### ISSUE TITLE
Hotwire Reloads and Login route triggering

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#65]
I login to my development store, and then load up my Hotwire App. Homepage loads perfect. I have done thing. I fire my code editor and change a CSS file. Hotwire Reloads the App and the chain of events that unfolds takes me back to login. Less than ideal? Is there something I can tweak to just have Hotwire reload the App without travelling to login during development cycles? 

    [ ShopifyApp | INFO | Shop Not Found ] Installed store  - fud.myshopify.com deduced from user session
    [ActionCable] Broadcasting to hotwire-reload: {:changed=>["/Users/fud/Documents/Workspace/Apps/2023/fud/web/app/assets/stylesheets/application.css"], :force_reload=>true}
    Hotwire::Livereload::ReloadChannel transmitting {"changed"=>["/Users/fud/Documents/Workspace/Apps/2023/fud/web/app/assets/stylesheets/application.css"], "force_reload"=>true} (via streamed from hotwire-reload)
    Finished "/cable" [WebSocket] for 127.0.0.1 at 2023-01-12 11:50:48 -0500
    Hotwire::Livereload::ReloadChannel stopped streaming from hotwire-reload
    Started GET "/home" for 127.0.0.1 at 2023-01-12 11:50:48 -0500
    Processing by HomeController#index as HTML
    [ ShopifyApp | WARN | Shop Not Found ] No cookies have been found - cookie name: shopify_app_session
    [ ShopifyApp | INFO | Shop Not Found ] Installed store  -  deduced from user session
    Redirected to https://fud.test/?return_to=%2Fhome
    Filter chain halted as :redirect_to_splash_page rendered or redirected
    Completed 302 Found in 13ms (ActiveRecord: 0.0ms | Allocations: 5673)
    Started GET "/?return_to=%2Fhome" for 127.0.0.1 at 2023-01-12 11:50:48 -0500
    Processing by SplashPageController#index as HTML
      Parameters: {"return_to"=>"/home"}
    Redirected to https://fud.test/login
    Filter chain halted as :check_shop_domain rendered or redirected
    Completed 302 Found in 0ms (ActiveRecord: 0.0ms | Allocations: 141)

**Comment by kirillplatonov** [comment]
Can't reproduce it with the latest version of the sample. The app stays on the same page after style changes and force reloading. Need more info on how to reproduce the problem.

**Comment by resistorsoftware** [comment]
ya. who knows... so much of the internal wiring is constantly changing, whatever that is, it is hard to repro. I just post it as a fact of things at that time. The logs tell a story, but not what is actually screwed up to generate the screwy logs.
