### ISSUE TITLE
App Bridge 3

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#69]
From Shopify, App Bridge 3 now supersedes the use of App Bridge Utils. In other words, we no longer add @shopify/app-bridge-utils but instead can just use @shopify/app-bridge and get the same utility.

**Comment by kirillplatonov** [comment]
`@shopify/app-bridge` doesn't provide `getSessionToken` method:
<img width="1512" alt="CleanShot 2023-02-09 at 23 00 35@2x" src="https://user-images.githubusercontent.com/839922/217912523-c7bb36ab-b393-4774-8eea-fd6c06c48b2d.png">

**Comment by resistorsoftware** [comment]
It does. You need only reference it. 

       import { getSessionToken } from "@shopify/app-bridge/utilities"

**Comment by kirillplatonov** [comment]
Got it. Thanks!

**Comment by resistorsoftware** [comment]
I would make PR's but my version of how I use this App is not really **this** app so much anymore, so it seems kinda pointless to me to clone it, fix up a small thing, and make a PR... but then again, I do use this Repo as a starting point, so I guess it does make sense to try and update it where it needs it.

**Comment by kirillplatonov** [comment]
I think it's useful not only as a starting point but also as a reference for app upgrades. It's very handy to have a clean sample that works with the latest Shopify changes. Especially for major upgrades like ShopifyAPI 10. So PRs even for small fixes are always welcome!

**Comment by resistorsoftware** [comment]
Heck ya.. Shopify API is already at 12.4 and keeps going up fast.
