### ISSUE TITLE
Supposedly slow App

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#74]
Just looking at some numbers this App generates inside Shopify. They are pointing out it is slow. Can anything be done to speed this App up? Is this a problem with Splashpage Controller or the ultimate root#home controller ??

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/123307/217924658-88dad9d2-fd10-4461-97bb-cf422953b7a3.png">

**Comment by scart88** [comment]
The Core Web Vitals metrics are recorded from all pages.
You will need to preload the LCP element (above the fold) and make sure it that element loads as fast as possible in the network timeline and lazyload everything else.

For example, you can use multiple lazy turbo_frames for everything that sits under the fold:

```
<%= turbo_frame_tag :onboarding_instructions, src: onboarding_instructions_path(shop: @shop_origin), loading: :lazy %>
```
