### ISSUE TITLE
All sorts of issues with this App now

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#75]
Updated to Shopify App 21.4.1 and now installs are terrible. I get 3 redirects before the App settles in as installed. OK. At least it installs. 

Not sure when Shopify changed their webhooks but the old pattern no longer works. With webhooks anyway, they are using the host environment on localhost installs as the destination address for webhooks even though my host is unreachable as I use named tunnels and ngrok, with puma dev. So my host is unreachable to webhooks as https://myapp.test and should be an override of https://myapp.ngrok.io but Shopify cannot apparently deal with that? 

Anyway.. the redirecting is terrible. Flashing up, down, left, right, yay! We're installed... sheesh... Anyone else experiencing this?

**Comment by scart88** [comment]
We have no issues with the webhooks (development/production), but we are using the Cloudflare tunnels for development.

```ruby
ShopifyApp.configure do |config|
  ...
  config.api_version = "2022-07"
  config.after_authenticate_job = { job: "Shopify::AfterAuthenticateJob", inline: true }
  config.reauth_on_access_scope_changes = true
  config.webhooks = [
    {topic: "products/delete", path: "webhooks/products_delete", format: "json"},
    {topic: "app/uninstalled", path: "webhooks/app_uninstalled", format: "json"},
  ]
end

Rails.application.config.after_initialize do
  if ShopifyApp.configuration.api_key.present? && ShopifyApp.configuration.secret.present?
     ShopifyApp::WebhooksManager.add_registrations
  end
end
```


```ruby
class ProductsDeleteJob < ActiveJob::Base
  extend ShopifyAPI::Webhooks::Handler

  class << self
    def handle(topic: nil, shop:, body:)
      perform_later(topic: topic, shop_domain: shop, webhook: body)
    end
  end

  def perform(topic: nil, shop_domain:, webhook:)
    shop = Shop.find_by(shopify_domain: shop_domain)

    if shop.nil?
      logger.error("#{self.class} failed: cannot find shop with domain '#{shop_domain}'")

      raise ActiveRecord::RecordNotFound, "Shop Not Found"
    end

    puts "PRODUCT DELETE JOB"

  end
end
```
