### ISSUE TITLE
Hotwire Reloading

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#77]
In the Gemfile the Hotwire Reloading gem is loaded by bundler in the front-end section of gems, but to my mind, that gem only belongs in the development group as you'd never be using Hotwire Reloading in production, so why have it everywhere? Am I missing something key about using Hotwire Reload?

**Comment by kirillplatonov** [comment]
It's used only in development mode so it's safe to move the gem to `development` group. I updated Gemfile in repo.
