### ISSUE TITLE
Shopify cli command "shopify app connect" does not exist

### ISSUE THREAD

**Issue by gsempe** [kirillplatonov/shopify-hotwire-sample#78]
With Shopify cli version 3.45.0 the command `shopify app connect` used in the README does not exist.
What command should I use?

For reference my terminal output:

```bash
shopify version
Current Shopify CLI version: 3.45.0

shopify app connect     
?  Command `app connect` not found. Did you mean `config autocorrect on`?

>  (y) Yes, confirm
   (n) No, cancel

```

**Comment by kirillplatonov** [comment]
Not sure to be honest. I will take a look at the Shopify CLI v3 to upgrade in a few weeks.

For now, you can manually create an app in Partner Dashboard and the `.env` file using `.env.example` as a reference.
