### ISSUE TITLE
Webhooks don't seem to show up

### ISSUE THREAD

**Issue by resistorsoftware** [kirillplatonov/shopify-hotwire-sample#79]
I have a config like this:

    config.webhooks = [
      { topic: "orders/create", path: "webhooks/orders_create" },
      { topic: "app/uninstalled", path: "webhooks/app_uninstalled" },
      { topic: "orders/paid", path: "webhooks/orders_paid" },
    ]
    
So I think to myself, great! When I check in with my App install, I have the app_uninstalled code running perfect, and the count of webhooks returns as 1... for that topic, but the two other topics, for orders/paid and orders/create never get created, and am wondering why not? I remain a little stumped here. No errors get thrown about missing topics, and I have the code for those two webhooks in place... just, nothing shows up on the App when testing installs... 

Any clues about what to maybe look for? Logs show the webhook registration process all running, no errors thrown.. but only the one topic is ever installed, the app/uninstalled one. Why only that one?

**Comment by aaronwhitman** [comment]
I use a rake task that uses a ShopifyAPI temp session to view all installed web hooks like this:

`ShopifyAPI::Webhook.all.to_json`

This shows me all topics scoped to my app. Wondering if you are seeing web hooks scoped to your app, or only the default Shopify web hook for app_uninstalled? I seem to recall "app/uninstalled" was created by default in the past, is this still the case?

**Comment by resistorsoftware** [comment]
I am thinking that the reason those orders/* do not get created is due to Shopify throwing a 403 error since orders access protected customer data, and the robots at Shopify never cleared this public App to have access to protected customer data yet? That is all I can think of... certainly nothing else comes to mind!

**Comment by aaronwhitman** [comment]
Makes sense. I have had those permissions for some time, and have not run into this scenario. Sounds like you found the most likely cause.

**Comment by resistorsoftware** [comment]
It is so screwy. You'd think the code they layer in there would barf out some kind of warning when it encounters things it cannot handle. I ask the App to create 3 Webhooks, tell me you created 0, 1, 2 or 3 webhooks. Leaving my logs blank is not helpful, forcing me to audit these things... that is for sure.

**Comment by resistorsoftware** [comment]
So earlier I had 403 problems on Customer records, due to not having the privacy flag set, but I just repeated a GET and got my data. So in my joy at that, I uninstalled - reinstalled that App and sadly, boooo... still no orders/paid or orders/create webhooks get auto-set by Shopify... which sucks... if the privacy flag is indeed lifted on this App, why do webhooks on orders not install for an App with write_orders scope????

**Comment by kirillplatonov** [comment]
Closing as it's not related to the repo. You'd better ask it in https://github.com/Shopify/shopify_app
