### ISSUE TITLE
OAuth Error, Same site cookies

### ISSUE THREAD

**Issue by david-gero-fn** [kirillplatonov/shopify-hotwire-sample#81]
I'm testing the sample app, and I run into the Same Site Cookies error. - Even if I enable 3rd party cookies in my browser. 

![image](https://github.com/kirillplatonov/shopify-hotwire-sample/assets/130745540/fae3e2a6-b9f1-4cd8-8ce8-1ee4e97ece58)

`oauth_error=same_site_cookies`

I found that there is already set to `none` here:
https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/config/application.rb#L22-L23

What I also tried
- Set `none` in the `session_store.rb`
`Rails.application.config.session_store(:cookie_store, key: '_example_session', expire_after: 14.days, secure: true, same_site: :none`

- Change the session_store to redis_store, `session_store :redis_store`

Similar question before
https://community.shopify.com/c/shopify-discussions/oauth-error-same-site-cookies/m-p/1788658

Any idea?

**Comment by rbarreca** [comment]
I'm facing the same thing. @kirillplatonov do you have any guidance? Happy to sponsor the work. Lmk!

**Comment by kirillplatonov** [comment]
Are you getting this error with a sample app? Could you please include reproduction steps cause I don't see this error in sample or in any of my apps.

And which browser do you use?

**Comment by crobbo** [comment]
Has anyone solved this? I'm getting the same error. 

1) Follow the instructions in the readme. 
2) Log in to partner dashboard
3) Get development store url
4) Visit cloudflare forwarding URL, enter store url and install app
5) The app seems to install but throws the cookies error
6) Try opening the app again, same error

I tried this with Chrome, Firefox and Brave.

**Comment by kirillplatonov** [comment]
While working on Shopify Hotwire Template I encountered this issue too after generating new app with Shopify CLI. It's not related to the Rails app and caused by Shopify CLI configuration. After hours of investigations I found solution and documented it in new private template repository. You can get an access to Shopify Hotwire Template repo by [becoming a Github Sponsor](https://github.com/sponsors/kirillplatonov). This will support my efforts to keep app template up to date with constant Shopify changes.

**Comment by EmersonEmerson** [comment]
I just had this exact error and "cookie" message with a fresh install and noticed the following error in the app logs during the redirect loop:

`web.1  | Error while billing the store: [{"field"=>nil, "message"=>"Apps without a public distribution cannot use the Billing API"}]`

To fix this, I did the following:

1. In your Partners dashboard, navigate to Apps > [Your app]. In the left sidebar, select "Distribution" 
2. On the subsequent page, declare the app type as "public" and click save.
3. Restart app server and enjoy.

(Still support Kirill and his hard work on this repo by [becoming a Github Sponsor](https://github.com/sponsors/kirillplatonov).
