### ISSUE TITLE
Access to private shopify-hotwire repo

### ISSUE THREAD

**Issue by rbarreca** [kirillplatonov/shopify-hotwire-sample#85]
Hi @kirillplatonov, I've become a small sponsor. Could I get access to the private shopify-hotwire repo to see any updates?

**Comment by kirillplatonov** [comment]
Hi @rbarreca. Thank you for becoming a sponsor!
To get an access to private app template $49+ tier is required:
<img width="356" alt="CleanShot 2023-10-01 at 08 32 55@2x" src="https://github.com/kirillplatonov/shopify-hotwire-sample/assets/839922/c956c937-3f4f-4325-a3cd-8ea1a92b7c78">

Feel free to [email me](mailto:mail@kirillplatonov.com) in case of questions regarding sponsorship or private app template.

**Comment by rbarreca** [comment]
Got it, thanks for clarifying.
