### ISSUE TITLE
This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser, or contacting the developer to get support.

### ISSUE THREAD

**Issue by tayyab910629** [kirillplatonov/shopify-hotwire-sample#86]
everytime i try to install i get this error when its redirect after install, this is the callback url

https://lowstockalert.ngrok.app/auth/shopify/callback

![image](https://github.com/kirillplatonov/shopify-hotwire-sample/assets/21190055/a781d7e3-f165-4f7c-8c67-e02befa764a8)

**Comment by guilhermeprokisch** [comment]
I had the same problem, but after creating a clean store (with sample data) and a clean app, it worked.
