### ISSUE TITLE
cloudflare is down what is the alternate we can do with yarn dev

### ISSUE THREAD

**Issue by tayyab910629** [kirillplatonov/shopify-hotwire-sample#87]
cloudflare is down what is the alternate we can do with yarn dev, i want to use ngrock with yarn dev, how its possible?

![cloud1](https://github.com/kirillplatonov/shopify-hotwire-sample/assets/21190055/5ac4e2c5-e76c-4738-be87-cd345aa222b5)

**Comment by kirillplatonov** [comment]
```bash
yarn dev --tunnel-url=https://[TUNNEL_ADDRESS]:8080
```

**Comment by tayyab910629** [comment]
yes its working with this now, may i know why we added 8080 port here instaed of 3000

**Comment by kirillplatonov** [comment]
If you use web server with tunnel then it should be 3000

**Comment by tayyab910629** [comment]
When i try like this yarn dev --tunnel-url=https://precious-goblin-greatly.ngrok-free.app:3000
its not working, its says port already in use but when i run rails s, its working. how can i make it work with yarn dev.

![image](https://github.com/kirillplatonov/shopify-hotwire-sample/assets/21190055/e3c3f682-78e6-484e-ae70-ce7588359374)
